language: node_js
node_js:
  - "10.15.0"

branches:
  only:
    - master
    - develop

before_script:
  - yarn install --frozen-lockfile

script:
  - yarn build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: master
  local_dir: dist
